<template><div><h1 id="配置指南" tabindex="-1"><a class="header-anchor" href="#配置指南"><span>配置指南</span></a></h1>
<p>本指南将详细介绍如何配置 NucleusX-Core 的各个模块。</p>
<h2 id="kit-配置" tabindex="-1"><a class="header-anchor" href="#kit-配置"><span>Kit 配置</span></a></h2>
<p>Kit 是 NucleusX-Core 的核心配置对象，它集成了所有平台特定的实现。</p>
<h3 id="基础-kit-配置" tabindex="-1"><a class="header-anchor" href="#基础-kit-配置"><span>基础 Kit 配置</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> createRuntime<span class="token punctuation">,</span> <span class="token keyword">type</span> <span class="token class-name">IKit</span> <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@nucleusx/core'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> myKit<span class="token operator">:</span> IKit <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  platformBridge<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 平台桥接器配置</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  storeEngine<span class="token operator">:</span> myStoreEngine<span class="token punctuation">,</span></span>
<span class="line">  request<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 请求配置</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  router<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 路由配置</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  logger<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 日志配置</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  appInfo<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 应用信息</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="平台桥接器-platformbridge" tabindex="-1"><a class="header-anchor" href="#平台桥接器-platformbridge"><span>平台桥接器 (PlatformBridge)</span></a></h2>
<p>平台桥接器是连接 NucleusX-Core 与具体平台的桥梁。</p>
<h3 id="核心接口" tabindex="-1"><a class="header-anchor" href="#核心接口"><span>核心接口</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">interface</span> <span class="token class-name">IPlatformBridge</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token comment">// 消息提示</span></span>
<span class="line">  <span class="token function-variable function">showToast</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token operator">:</span> ToastOptions<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function-variable function">showLoading</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token operator">:</span> LoadingOptions<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function-variable function">hideLoading</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function-variable function">showModal</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token operator">:</span> ModalOptions<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span></span>
<span class="line">  </span>
<span class="line">  <span class="token comment">// 存储</span></span>
<span class="line">  <span class="token function-variable function">getStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span>key<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">any</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function-variable function">setStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span>key<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> data<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function-variable function">removeStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span>key<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function-variable function">clearStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span></span>
<span class="line">  </span>
<span class="line">  <span class="token comment">// 系统信息</span></span>
<span class="line">  <span class="token function-variable function">getSystemInfo</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> SystemInfo<span class="token punctuation">;</span></span>
<span class="line">  </span>
<span class="line">  <span class="token comment">// 导航</span></span>
<span class="line">  <span class="token function-variable function">navigateTo</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token operator">:</span> NavigateOptions<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function-variable function">redirectTo</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token operator">:</span> NavigateOptions<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function-variable function">navigateBack</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token operator">?</span><span class="token operator">:</span> BackOptions<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span></span>
<span class="line">  </span>
<span class="line">  <span class="token comment">// 其他平台 API...</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="小程序平台桥接器示例" tabindex="-1"><a class="header-anchor" href="#小程序平台桥接器示例"><span>小程序平台桥接器示例</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> miniProgramBridge<span class="token operator">:</span> IPlatformBridge <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token function-variable function">showToast</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">showToast</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">showLoading</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">showLoading</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">hideLoading</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">hideLoading</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">showModal</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">showModal</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">getStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span>key<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">getStorageSync</span><span class="token punctuation">(</span>key<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">setStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span>key<span class="token punctuation">,</span> data<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">setStorageSync</span><span class="token punctuation">(</span>key<span class="token punctuation">,</span> data<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">removeStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span>key<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">removeStorageSync</span><span class="token punctuation">(</span>key<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">clearStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">clearStorageSync</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">getSystemInfo</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">getSystemInfoSync</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">navigateTo</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">navigateTo</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">redirectTo</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">redirectTo</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">navigateBack</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">navigateBack</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="请求模块配置" tabindex="-1"><a class="header-anchor" href="#请求模块配置"><span>请求模块配置</span></a></h2>
<p>请求模块提供了统一的网络请求接口。</p>
<h3 id="基础配置" tabindex="-1"><a class="header-anchor" href="#基础配置"><span>基础配置</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> requestConfig <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  baseUrl<span class="token operator">:</span> <span class="token string">'https://api.example.com'</span><span class="token punctuation">,</span></span>
<span class="line">  adapter<span class="token operator">:</span> myAdapter<span class="token punctuation">,</span></span>
<span class="line">  timeout<span class="token operator">:</span> <span class="token number">5000</span><span class="token punctuation">,</span></span>
<span class="line">  headers<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token string-property property">'Content-Type'</span><span class="token operator">:</span> <span class="token string">'application/json'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  errorMode<span class="token operator">:</span> <span class="token string">'wrapped'</span> <span class="token keyword">as</span> <span class="token keyword">const</span><span class="token punctuation">,</span> <span class="token comment">// 'legacy' | 'wrapped'</span></span>
<span class="line">  <span class="token function-variable function">isBizSuccess</span><span class="token operator">:</span> <span class="token punctuation">(</span>response<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 自定义业务成功判断逻辑</span></span>
<span class="line">    <span class="token keyword">return</span> response<span class="token punctuation">.</span>statusCode <span class="token operator">===</span> <span class="token number">200</span> <span class="token operator">&amp;&amp;</span> </span>
<span class="line">           response<span class="token punctuation">.</span>data <span class="token operator">&amp;&amp;</span> </span>
<span class="line">           response<span class="token punctuation">.</span>data<span class="token punctuation">.</span>code <span class="token operator">===</span> <span class="token number">200</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="请求适配器配置" tabindex="-1"><a class="header-anchor" href="#请求适配器配置"><span>请求适配器配置</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> myAdapter<span class="token operator">:</span> RequestAdapter <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token function-variable function">request</span><span class="token operator">:</span> <span class="token punctuation">(</span>config<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 实现平台特定的请求逻辑</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token function">platformSpecificRequest</span><span class="token punctuation">(</span>config<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="中间件配置" tabindex="-1"><a class="header-anchor" href="#中间件配置"><span>中间件配置</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> request <span class="token operator">=</span> <span class="token function">createRequest</span><span class="token punctuation">(</span>requestConfig<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 添加自定义中间件</span></span>
<span class="line">request<span class="token punctuation">.</span><span class="token function">use</span><span class="token punctuation">(</span><span class="token keyword">async</span> <span class="token punctuation">(</span>context<span class="token punctuation">,</span> next<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token comment">// 请求前处理</span></span>
<span class="line">  context<span class="token punctuation">.</span>request<span class="token punctuation">.</span>headers <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token operator">...</span>context<span class="token punctuation">.</span>request<span class="token punctuation">.</span>headers<span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'X-Request-ID'</span><span class="token operator">:</span> <span class="token function">generateRequestId</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">  </span>
<span class="line">  <span class="token keyword">await</span> <span class="token function">next</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  </span>
<span class="line">  <span class="token comment">// 响应后处理</span></span>
<span class="line">  <span class="token keyword">if</span> <span class="token punctuation">(</span>context<span class="token punctuation">.</span>response<span class="token operator">?.</span>statusCode <span class="token operator">===</span> <span class="token number">401</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 处理认证失败</span></span>
<span class="line">    <span class="token keyword">await</span> <span class="token function">handleTokenRefresh</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="路由模块配置" tabindex="-1"><a class="header-anchor" href="#路由模块配置"><span>路由模块配置</span></a></h2>
<p>路由模块支持三种运行模式。</p>
<h3 id="模式配置" tabindex="-1"><a class="header-anchor" href="#模式配置"><span>模式配置</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> routerConfig <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  mode<span class="token operator">:</span> <span class="token string">'auto'</span> <span class="token keyword">as</span> <span class="token keyword">const</span><span class="token punctuation">,</span> <span class="token comment">// 'spa' | 'mpa' | 'auto'</span></span>
<span class="line">  <span class="token function-variable function">pagesFetcher</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token function">fetchPagesConfig</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function-variable function">userPermissionsProvider</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token function">getMyPermissions</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  appConfig<span class="token operator">:</span> <span class="token punctuation">{</span> </span>
<span class="line">    startPage<span class="token operator">:</span> <span class="token string">'home'</span><span class="token punctuation">,</span></span>
<span class="line">    defaultTransition<span class="token operator">:</span> <span class="token string">'slide'</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  animation<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    duration<span class="token operator">:</span> <span class="token number">500</span><span class="token punctuation">,</span></span>
<span class="line">    easing<span class="token operator">:</span> <span class="token string">'cubic-bezier(0.25, 1, 0.5, 1)'</span><span class="token punctuation">,</span></span>
<span class="line">    enabled<span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span></span>
<span class="line">    type<span class="token operator">:</span> <span class="token string">'perspective'</span> <span class="token keyword">as</span> <span class="token keyword">const</span> <span class="token comment">// 'perspective' | 'slide' | 'fade' | 'none'</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="spa-模式" tabindex="-1"><a class="header-anchor" href="#spa-模式"><span>SPA 模式</span></a></h3>
<p>纯 SPA 模式，所有跳转使用虚拟页面栈：</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> spaConfig <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token operator">...</span>routerConfig<span class="token punctuation">,</span></span>
<span class="line">  mode<span class="token operator">:</span> <span class="token string">'spa'</span> <span class="token keyword">as</span> <span class="token keyword">const</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="mpa-模式" tabindex="-1"><a class="header-anchor" href="#mpa-模式"><span>MPA 模式</span></a></h3>
<p>纯 MPA 模式，所有跳转调用平台原生导航 API：</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> mpaConfig <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token operator">...</span>routerConfig<span class="token punctuation">,</span></span>
<span class="line">  mode<span class="token operator">:</span> <span class="token string">'mpa'</span> <span class="token keyword">as</span> <span class="token keyword">const</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="auto-模式-默认" tabindex="-1"><a class="header-anchor" href="#auto-模式-默认"><span>Auto 模式（默认）</span></a></h3>
<p>自动模式，根据路径亲和性自动判定 SPA/MPA：</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> autoConfig <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token operator">...</span>routerConfig<span class="token punctuation">,</span></span>
<span class="line">  mode<span class="token operator">:</span> <span class="token string">'auto'</span> <span class="token keyword">as</span> <span class="token keyword">const</span> <span class="token comment">// 默认值</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="日志模块配置" tabindex="-1"><a class="header-anchor" href="#日志模块配置"><span>日志模块配置</span></a></h2>
<p>日志模块支持多通道输出。</p>
<h3 id="基础配置-1" tabindex="-1"><a class="header-anchor" href="#基础配置-1"><span>基础配置</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> loggerConfig <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  level<span class="token operator">:</span> <span class="token string">'info'</span> <span class="token keyword">as</span> <span class="token keyword">const</span><span class="token punctuation">,</span> <span class="token comment">// 'trace' | 'debug' | 'info' | 'warn' | 'error'</span></span>
<span class="line">  transports<span class="token operator">:</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token keyword">new</span> <span class="token class-name">ConsoleTransport</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token keyword">new</span> <span class="token class-name">StorageTransport</span><span class="token punctuation">(</span><span class="token punctuation">{</span> maxEntries<span class="token operator">:</span> <span class="token number">1000</span> <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">  <span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">  defaultContext<span class="token operator">:</span> <span class="token string">'App'</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="输出通道配置" tabindex="-1"><a class="header-anchor" href="#输出通道配置"><span>输出通道配置</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token comment">// 控制台输出（开发环境）</span></span>
<span class="line"><span class="token keyword">const</span> consoleTransport <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ConsoleTransport</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">  <span class="token function-variable function">format</span><span class="token operator">:</span> <span class="token punctuation">(</span>entry<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>entry<span class="token punctuation">.</span>level<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">] </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>entry<span class="token punctuation">.</span>context<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>entry<span class="token punctuation">.</span>message<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 本地存储（生产环境）</span></span>
<span class="line"><span class="token keyword">const</span> storageTransport <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">StorageTransport</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">  maxEntries<span class="token operator">:</span> <span class="token number">1000</span><span class="token punctuation">,</span></span>
<span class="line">  storageKey<span class="token operator">:</span> <span class="token string">'app_logs'</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// HTTP 传输（上报服务）</span></span>
<span class="line"><span class="token keyword">const</span> httpTransport <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">HttpTransport</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">  endpoint<span class="token operator">:</span> <span class="token string">'https://logs.example.com/api/logs'</span><span class="token punctuation">,</span></span>
<span class="line">  batchSize<span class="token operator">:</span> <span class="token number">10</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="状态管理配置" tabindex="-1"><a class="header-anchor" href="#状态管理配置"><span>状态管理配置</span></a></h2>
<p>状态管理模块需要配置底层引擎。</p>
<h3 id="引擎配置" tabindex="-1"><a class="header-anchor" href="#引擎配置"><span>引擎配置</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> storeConfig <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token comment">// 使用预配置的引擎</span></span>
<span class="line">  engine<span class="token operator">:</span> myStoreEngine</span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="自定义引擎实现" tabindex="-1"><a class="header-anchor" href="#自定义引擎实现"><span>自定义引擎实现</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">class</span> <span class="token class-name">MyStoreEngine</span> <span class="token keyword">implements</span> <span class="token class-name">StoreEngine</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token function">define</span><span class="token punctuation">(</span>id<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> options<span class="token operator">:</span> StoreOptions<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 实现引擎逻辑</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token function">createPlatformSpecificStore</span><span class="token punctuation">(</span>id<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="完整配置示例" tabindex="-1"><a class="header-anchor" href="#完整配置示例"><span>完整配置示例</span></a></h2>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> createRuntime<span class="token punctuation">,</span> <span class="token keyword">type</span> <span class="token class-name">IKit</span> <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@nucleusx/core'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ConsoleTransport<span class="token punctuation">,</span> StorageTransport <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./transports'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> myWxAdapter <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./adapters'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> mobxEngine <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./engines'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> completeKit<span class="token operator">:</span> IKit <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  platformBridge<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function-variable function">showToast</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">showToast</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">showLoading</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">showLoading</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">hideLoading</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">hideLoading</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">showModal</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">showModal</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">getStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span>key<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">getStorageSync</span><span class="token punctuation">(</span>key<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">setStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span>key<span class="token punctuation">,</span> data<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">setStorageSync</span><span class="token punctuation">(</span>key<span class="token punctuation">,</span> data<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">removeStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span>key<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">removeStorageSync</span><span class="token punctuation">(</span>key<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">clearStorageSync</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">clearStorageSync</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">getSystemInfo</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">getSystemInfoSync</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">navigateTo</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">navigateTo</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">redirectTo</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">redirectTo</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">navigateBack</span><span class="token operator">:</span> <span class="token punctuation">(</span>options<span class="token punctuation">)</span> <span class="token operator">=></span> wx<span class="token punctuation">.</span><span class="token function">navigateBack</span><span class="token punctuation">(</span>options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  storeEngine<span class="token operator">:</span> mobxEngine<span class="token punctuation">,</span></span>
<span class="line">  request<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    baseUrl<span class="token operator">:</span> <span class="token string">'https://api.example.com'</span><span class="token punctuation">,</span></span>
<span class="line">    adapter<span class="token operator">:</span> myWxAdapter<span class="token punctuation">,</span></span>
<span class="line">    timeout<span class="token operator">:</span> <span class="token number">10000</span><span class="token punctuation">,</span></span>
<span class="line">    headers<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token string-property property">'Content-Type'</span><span class="token operator">:</span> <span class="token string">'application/json'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token string-property property">'X-App-Version'</span><span class="token operator">:</span> <span class="token string">'1.0.0'</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">isBizSuccess</span><span class="token operator">:</span> <span class="token punctuation">(</span>response<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token keyword">return</span> response<span class="token punctuation">.</span>statusCode <span class="token operator">===</span> <span class="token number">200</span> <span class="token operator">&amp;&amp;</span> </span>
<span class="line">             response<span class="token punctuation">.</span>data<span class="token operator">?.</span>code <span class="token operator">===</span> <span class="token number">0</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">    errorMode<span class="token operator">:</span> <span class="token string">'wrapped'</span> <span class="token keyword">as</span> <span class="token keyword">const</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  router<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    mode<span class="token operator">:</span> <span class="token string">'auto'</span> <span class="token keyword">as</span> <span class="token keyword">const</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">pagesFetcher</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token function">fetchPagesConfig</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">userPermissionsProvider</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token function">getUserPermissions</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    appConfig<span class="token operator">:</span> <span class="token punctuation">{</span> </span>
<span class="line">      startPage<span class="token operator">:</span> <span class="token string">'home'</span><span class="token punctuation">,</span></span>
<span class="line">      defaultTransition<span class="token operator">:</span> <span class="token string">'slide'</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">    animation<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">      duration<span class="token operator">:</span> <span class="token number">300</span><span class="token punctuation">,</span></span>
<span class="line">      easing<span class="token operator">:</span> <span class="token string">'ease-in-out'</span><span class="token punctuation">,</span></span>
<span class="line">      enabled<span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span></span>
<span class="line">      type<span class="token operator">:</span> <span class="token string">'slide'</span> <span class="token keyword">as</span> <span class="token keyword">const</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  logger<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    level<span class="token operator">:</span> <span class="token string">'info'</span> <span class="token keyword">as</span> <span class="token keyword">const</span><span class="token punctuation">,</span></span>
<span class="line">    transports<span class="token operator">:</span> <span class="token punctuation">[</span></span>
<span class="line">      <span class="token keyword">new</span> <span class="token class-name">ConsoleTransport</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token keyword">new</span> <span class="token class-name">StorageTransport</span><span class="token punctuation">(</span><span class="token punctuation">{</span> maxEntries<span class="token operator">:</span> <span class="token number">2000</span> <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    defaultContext<span class="token operator">:</span> <span class="token string">'MyApp'</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  appInfo<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    appId<span class="token operator">:</span> <span class="token string">'wx123456'</span><span class="token punctuation">,</span></span>
<span class="line">    name<span class="token operator">:</span> <span class="token string">'My Application'</span><span class="token punctuation">,</span></span>
<span class="line">    version<span class="token operator">:</span> <span class="token string">'1.0.0'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 使用完整配置初始化运行时</span></span>
<span class="line"><span class="token keyword">const</span> runtime <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">createRuntime</span><span class="token punctuation">(</span>completeKit<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="环境特定配置" tabindex="-1"><a class="header-anchor" href="#环境特定配置"><span>环境特定配置</span></a></h2>
<p>您可以根据环境变量创建不同的配置：</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> getConfigByEnvironment <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> IKit <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">const</span> commonConfig <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 通用配置</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token keyword">switch</span> <span class="token punctuation">(</span>process<span class="token punctuation">.</span>env<span class="token punctuation">.</span><span class="token constant">NODE_ENV</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">case</span> <span class="token string">'development'</span><span class="token operator">:</span></span>
<span class="line">      <span class="token keyword">return</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token operator">...</span>commonConfig<span class="token punctuation">,</span></span>
<span class="line">        logger<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">          level<span class="token operator">:</span> <span class="token string">'debug'</span> <span class="token keyword">as</span> <span class="token keyword">const</span><span class="token punctuation">,</span></span>
<span class="line">          transports<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token keyword">new</span> <span class="token class-name">ConsoleTransport</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">]</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">        request<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">          <span class="token operator">...</span>commonConfig<span class="token punctuation">.</span>request<span class="token punctuation">,</span></span>
<span class="line">          baseUrl<span class="token operator">:</span> <span class="token string">'https://dev-api.example.com'</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">      <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">    </span>
<span class="line">    <span class="token keyword">case</span> <span class="token string">'production'</span><span class="token operator">:</span></span>
<span class="line">      <span class="token keyword">return</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token operator">...</span>commonConfig<span class="token punctuation">,</span></span>
<span class="line">        logger<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">          level<span class="token operator">:</span> <span class="token string">'warn'</span> <span class="token keyword">as</span> <span class="token keyword">const</span><span class="token punctuation">,</span></span>
<span class="line">          transports<span class="token operator">:</span> <span class="token punctuation">[</span></span>
<span class="line">            <span class="token keyword">new</span> <span class="token class-name">StorageTransport</span><span class="token punctuation">(</span><span class="token punctuation">{</span> maxEntries<span class="token operator">:</span> <span class="token number">1000</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token keyword">new</span> <span class="token class-name">HttpTransport</span><span class="token punctuation">(</span><span class="token punctuation">{</span> endpoint<span class="token operator">:</span> <span class="token string">'https://logs.example.com/api'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">          <span class="token punctuation">]</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">        request<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">          <span class="token operator">...</span>commonConfig<span class="token punctuation">.</span>request<span class="token punctuation">,</span></span>
<span class="line">          baseUrl<span class="token operator">:</span> <span class="token string">'https://api.example.com'</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">      <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">    </span>
<span class="line">    <span class="token keyword">default</span><span class="token operator">:</span></span>
<span class="line">      <span class="token keyword">return</span> commonConfig<span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="配置验证" tabindex="-1"><a class="header-anchor" href="#配置验证"><span>配置验证</span></a></h2>
<p>在生产环境中，建议添加配置验证：</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code class="language-typescript"><span class="line"><span class="token keyword">const</span> validateKit <span class="token operator">=</span> <span class="token punctuation">(</span>kit<span class="token operator">:</span> IKit<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">boolean</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token comment">// 验证必需字段</span></span>
<span class="line">  <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>kit<span class="token punctuation">.</span>platformBridge <span class="token operator">||</span> <span class="token operator">!</span>kit<span class="token punctuation">.</span>storeEngine<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">'Kit configuration is incomplete'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token boolean">false</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token comment">// 验证请求配置</span></span>
<span class="line">  <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>kit<span class="token punctuation">.</span>request<span class="token operator">?.</span>adapter <span class="token operator">||</span> <span class="token operator">!</span>kit<span class="token punctuation">.</span>request<span class="token operator">?.</span>baseUrl<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">'Request configuration is incomplete'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token boolean">false</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token comment">// 验证路由配置</span></span>
<span class="line">  <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>kit<span class="token punctuation">.</span>router<span class="token operator">?.</span>pagesFetcher <span class="token operator">||</span> <span class="token operator">!</span>kit<span class="token punctuation">.</span>router<span class="token operator">?.</span>userPermissionsProvider<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">'Router configuration is incomplete'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token boolean">false</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token keyword">return</span> <span class="token boolean">true</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 在初始化前验证配置</span></span>
<span class="line"><span class="token keyword">const</span> kit <span class="token operator">=</span> <span class="token function">getConfigByEnvironment</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token function">validateKit</span><span class="token punctuation">(</span>kit<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">const</span> runtime <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">createRuntime</span><span class="token punctuation">(</span>kit<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">Error</span><span class="token punctuation">(</span><span class="token string">'Invalid Kit configuration'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


